Repository Endphoenix/Q4SchachProjekt_BenjaminFilip_v2, pull requests merged in 2024-02, with the labels that each got.

#8 BugFixes, Verbesserungen und KillFunktion bei Pawn
  src/Pawn.java
  src/Piece.java
  src/pics/KillTarget.png
Labels: bug, enhancement, help wanted

#9 Bugfix bei tryKill() in Pawn, das was im vorherigen Commit etwas weniger "Zeichenintensiv" gemacht
  src/Bishop.java
  src/Board.java
  src/King.java
  src/Knight.java
  src/Pawn.java
  src/Queen.java
  src/Rook.java
  src/pics/BishopBlack.png
  src/pics/BishopWhite.png
  src/pics/KingBlack.png
  src/pics/KingWhite.png
  src/pics/KnightBlack.png
  src/pics/KnightWhite.png
  src/pics/QueenBlack.png
  src/pics/QueenWhite.png
  src/pics/RookBlack.png
  src/pics/RookWhite.png
Labels: enhancement

#10 Promote() + pawns-can-only-kill-pawns-fix
  src/Board.java
  src/Pawn.java
  src/Piece.java
Labels: enhancement

#11 Großes Update: Sounds, Neue Icons, GUI und erste Grundlagen für Gamelogic
  src/Board.java
  src/GameStatus.java
  src/Main.java
  src/Pawn.java
  src/Piece.java
  src/pics/Promotion.png
  src/pics/chess.png
  src/sfx/click.wav
  src/sfx/move.wav
  src/sfx/notify.wav
  src/sfx/promotion.wav
  src/sfx/start.wav
Labels: enhancement, help wanted

#13 Kleiner Bugfix
  src/Piece.java
Labels: bug

#14 2. Bugfix
  src/Pawn.java
Labels: bug

#15 Gamelogic fertig und Toolbar Funktionen hinzugefügt
  src/Board.java
  src/Pawn.java
  src/Piece.java
  src/pics/BlackWin.png
  src/pics/Castling.png
  src/pics/Warning.png
  src/pics/WhiteWin.png
Labels: enhancement

#16 benjamin
  src/Board.java
  src/King.java
  src/Piece.java
  src/Rook.java
Labels: bug, help wanted, good first issue

#18 first steps to better kill buttons
  src/Bishop.java
  src/King.java
  src/Knight.java
  src/Pawn.java
  src/Piece.java
  src/Queen.java
  src/Rook.java
Labels: bug
