Repository Endphoenix/Q4SchachProjekt_BenjaminFilip_v2, pull requests merged in 2024-03, with the labels that each got.

#19 Verlaufsfeld, ToolTips, Promotion Verbesserung, "Info-Button"
  src/Bishop.java
  src/Board.java
  src/King.java
  src/Knight.java
  src/Pawn.java
  src/Piece.java
  src/Queen.java
  src/Rook.java
Labels: bug, enhancement

#20 KillButtons enhanced
  src/Bishop.java
  src/King.java
  src/Knight.java
  src/Pawn.java
  src/Piece.java
  src/Queen.java
  src/Rook.java
Labels: enhancement

#21 EnPassant + Tooltip for KillButtons
  src/Bishop.java
  src/King.java
  src/Knight.java
  src/Pawn.java
  src/Piece.java
  src/Queen.java
  src/Rook.java
Labels: enhancement

#22 Bugfix of castling
  src/King.java
  src/Piece.java
Labels: enhancement

#23 Verlaufsfeld gefixed
  src/Board.java
Labels: enhancement

#26 UPDATE: Spiel speichern und laden
  src/Board.java
  src/GameStatus.java
Labels: enhancement, help wanted
